### ISSUE TITLE
你好，在fragment中切换会是布局变为

### ISSUE THREAD

**Issue by liubing67** [Proton626/FakeCardView#1]
![image](https://user-images.githubusercontent.com/16477950/31375401-f9b77154-add3-11e7-9e03-6ad22610ed98.png)
如果在fragment中使用的话，在onCreateView方法中加if (view==null)
        {
            view =inflater.inflate(R.layout.fragment_four, container, false);
        }这个if语句会使布局变为空白，同样，在fragment中点击进去下一个页面，再返回的时候也是如此

![image](https://user-images.githubusercontent.com/16477950/31384796-258b17c6-adf3-11e7-91ae-11965d9aad4f.png)
当测试手机是21以上的时候有上述情况

**Comment by wsybupt** [comment]
我也出现了空白的情况 请问怎么解决？

**Comment by liubing67** [comment]
https://github.com/loopeer/shadow
